# Generated by Django 5.0.1 on 2024-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0022_alter_movie_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='viewed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
