# Generated by Django 5.0.1 on 2024-12-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0025_movieclick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieclick',
            name='interaction_type',
        ),
    ]
